import json
from collections import defaultdict
from datetime import date

from .parser import ParsedRule

LAYER_VERSION = "4.5"
NAVIGATOR_VERSION = "4.9"
ATTACK_VERSION = "14"

COVERED_COLOR = "#31a354"   # green


def build_layer(rules: list[ParsedRule], layer_name: str = "Detection Coverage") -> dict:
    technique_rules: dict[str, list[str]] = defaultdict(list)

    for rule in rules:
        for technique in rule.techniques:
            technique_rules[technique].append(rule.title)

    techniques = []
    for technique_id, covering_rules in technique_rules.items():
        entry = {
            "techniqueID": technique_id,
            "score": len(covering_rules),
            "color": COVERED_COLOR,
            "comment": "\n".join(covering_rules),
            "enabled": True,
            "metadata": [],
            "links": [],
            "showSubtechniques": False,
        }
        techniques.append(entry)

    return {
        "name": layer_name,
        "versions": {
            "attack": ATTACK_VERSION,
            "navigator": NAVIGATOR_VERSION,
            "layer": LAYER_VERSION,
        },
        "domain": "enterprise-attack",
        "description": f"Generated by spl-coverage-map on {date.today()}",
        "filters": {"platforms": ["Windows", "Linux", "macOS", "Network", "Cloud"]},
        "sorting": 0,
        "layout": {"layout": "side", "aggregateFunction": "sum", "showID": True, "showName": True},
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffffff", COVERED_COLOR],
            "minValue": 0,
            "maxValue": max((len(v) for v in technique_rules.values()), default=1),
        },
        "legendItems": [{"label": "Has detection", "color": COVERED_COLOR}],
        "metadata": [],
        "links": [],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }


def render_summary(rules: list[ParsedRule]) -> str:
    from collections import defaultdict

    technique_rules: dict[str, list[str]] = defaultdict(list)
    all_tactics: set[str] = set()

    covered_tactics: set[str] = set()

    for rule in rules:
        for technique in rule.techniques:
            technique_rules[technique].append(rule.title)
        for tactic in rule.tactics:
            covered_tactics.add(tactic)

    all_tactics = {
        "reconnaissance", "resource-development", "initial-access", "execution",
        "persistence", "privilege-escalation", "defense-evasion", "credential-access",
        "discovery", "lateral-movement", "collection", "command-and-control",
        "exfiltration", "impact",
    }

    lines = [f"Techniques covered: {len(technique_rules)}"]
    for tech, rule_titles in sorted(technique_rules.items()):
        lines.append(f"  {tech:<12} {', '.join(rule_titles)}")

    gap_tactics = sorted(all_tactics - covered_tactics)
    if gap_tactics:
        lines.append("\nTactics with no coverage:")
        for tactic in gap_tactics:
            lines.append(f"  {tactic}")

    return "\n".join(lines)


def write_layer(layer: dict, output_path) -> None:
    with open(output_path, "w") as f:
        json.dump(layer, f, indent=2)
